name: Deploy

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  check-deploy:
    if: >
      github.event.pull_request.merged == true &&
      !contains(github.event.pull_request.labels.*.name, 'no-block')
    runs-on: ubuntu-latest
    outputs:
      proceed: true
    steps:
      - run: echo "Merge allowed — continuing to approval"

  approve:
    needs: check-deploy
    if: needs.check-deploy.outputs.proceed == 'true'
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - run: echo "Manual approval granted"

  deploy:
    needs: approve
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying to production..."
