name: Deployment

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  check-deploy:
    if: >
      github.event.pull_request.merged == true &&
      !contains(github.event.pull_request.labels.*.name, 'no-block')
    runs-on: ubuntu-latest
    outputs:
      DEPLOY_ALLOWED: true
    steps:
      - run: echo "Merge allowed, proceeding to deploy..."

  approve-production:
    needs: check-deploy
    if: needs.check-deploy.outputs.DEPLOY_ALLOWED == 'true'
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Await approval to deploy
        run: echo "Deployment approved"

  deploy:
    needs: approve-production
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Fake deploy step
        run: echo "🚀 Deploying application..."
