name: Build and Push Docker image

on:
  push:
    branches: [master]
    paths:
      - Dockerfile
      - package.json
      - tsconfig.json
      - tests/**
      - utils/**
      - playwright.config.ts
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/zerodayd/playwright-template:latest
          provenance: false
