name: no-block-check

on:
  workflow_run:
    workflows: ["Playwright Tests"]
    types:
      - completed

  pull_request:
    types: [labeled, unlabeled, synchronize, reopened]

jobs:
  no-block:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v3

      - name: Determine PR number
        id: pr
        run: |
          if [ "${{ github.event_name }}" = "workflow_run" ]; then
            echo "PR_NUMBER=$(jq '.[0].number' <<< '${{ toJson(github.event.workflow_run.pull_requests) }}')" >> "$GITHUB_OUTPUT"
          else
            echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Check if Playwright Tests passed or no-block label is set
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ steps.pr.outputs.PR_NUMBER }}

          if [ "${{ github.event_name }}" = "workflow_run" ] && [ "${{ github.event.workflow_run.conclusion }}" = "success" ]; then
            exit 0
          fi

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            RUN_STATUS=$(gh run list --workflow="Playwright Tests" --json status,conclusion,event -L 5 | jq -r \
              '[.[] | select(.event=="pull_request")][0].conclusion')

            if [ "$RUN_STATUS" = "success" ]; then
              exit 0
            elif [ -z "$RUN_STATUS" ]; then
              echo "No Playwright Tests run found. Assuming not yet run."
            fi
          fi

          LABELS=$(gh pr view "$PR_NUMBER" --json labels --jq '.labels[].name' || echo "[]")

          if echo "$LABELS" | grep -q "no-block"; then
            exit 0
          else
            exit 1
          fi
