name: no-block-check

on:
  workflow_run:
    workflows: ["Playwright Tests"]
    types:
      - completed

jobs:
  no-block:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v3

      - name: Check if Playwright Tests passed or no-block label is set
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Playwright Tests result: ${{ github.event.workflow_run.conclusion }}"

          if [ "${{ github.event.workflow_run.conclusion }}" = "success" ]; then
            echo "✅ Tests passed, merge allowed."
            exit 0
          fi
          
          PR_NUMBER=$(jq '.[0].number' <<< '${{ toJson(github.event.workflow_run.pull_requests) }}')
          echo "PR number: $PR_NUMBER"
          LABELS=$(gh pr view "$PR_NUMBER" --json labels --jq '.labels[].name' || echo "[]")
          echo "Labels: $LABELS"

          if echo "$LABELS" | grep -q "no-block"; then
            echo "⚠️ Tests failed, but 'no-block' label found — merge allowed."
            exit 0
          else
            echo "❌ Tests failed and no 'no-block' label — merge blocked."
            exit 1
          fi
