name: no-block-check

on:
  workflow_run:
    workflows: ["Playwright Tests"]
    types:
      - completed

  pull_request:
    types: [labeled, unlabeled, synchronize, reopened]

jobs:
  no-block:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v3

      - name: Determine PR number
        id: pr
        run: |
          if [ "${{ github.event_name }}" = "workflow_run" ]; then
            echo "PR_NUMBER=$(jq '.[0].number' <<< '${{ toJson(github.event.workflow_run.pull_requests) }}')" >> "$GITHUB_OUTPUT"
          else
            echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Check if Playwright Tests passed or no-block label is set
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ steps.pr.outputs.PR_NUMBER }}
          echo "PR number: $PR_NUMBER"

          if [ "${{ github.event_name }}" = "workflow_run" ]; then
            echo "Playwright Tests result: ${{ github.event.workflow_run.conclusion }}"
            if [ "${{ github.event.workflow_run.conclusion }}" = "success" ]; then
              echo "✅ Tests passed, merge allowed."
              exit 0
            fi
          fi

          LABELS=$(gh pr view "$PR_NUMBER" --json labels --jq '.labels[].name' || echo "[]")
          echo "Labels: $LABELS"

          if echo "$LABELS" | grep -q "no-block"; then
            echo "⚠️ Tests failed or are pending, but 'no-block' label found — merge allowed."
            exit 0
          else
            echo "❌ Merge blocked: no-block label not present and tests failed or pending."
            exit 1
          fi
